version: '3'
services:
  smart-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: smart.ucsd.edu
      VIRTUAL_PORT: 6213
      LETSENCRYPT_HOST: smart.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net