version: '3'
services:
  smart-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: smart.gnps2.org
      VIRTUAL_PORT: 6213
      LETSENCRYPT_HOST: smart.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net