services:
  smart-web:
    build: .
    ports:
      - "6213:5000"
    command: /app/run_server.sh
    networks:
      - default
      - nginx-net
    volumes:
        #- ./SMART_Classic:/src/SMART_Classic:ro
        - ./logs/:/app/logs
        - ./tempuploads/:/app/tempuploads

  smartclassic-redis:
    image: redis
    networks:
      - default

  smartclassic-rabbitmq:
    image: rabbitmq:latest
    networks:
      - default

  smartclassic-worker:
    build:
      context: .
      dockerfile: classic.Dockerfile
    container_name: smartclassic-worker
    volumes:
        - ./SMART_Classic:/src/SMART_Classic
        - ./tempuploads/:/src/tempuploads
    command: /src/run_smartclassic_celery_worker.sh
    restart: on-failure
    depends_on: 
      - smartclassic-redis
      - smartclassic-rabbitmq
    networks:
      - default


networks:
  nginx-net:
    name: nginx-net
    external: true