version: '3'

services:
  smart-web:
    build: .
    ports:
      - "6213:5000"
    command: /app/run_server.sh
    networks:
      - default
      - nginx-net
    volumes:
        - ./SMART_Finder:/SMART_Finder
        - ./logs/:/app/logs
        - ./tempuploads/:/app/tempuploads
    environment:
      VIRTUAL_HOST: mingwangbeta.ucsd.edu
      VIRTUAL_PORT: 6213
      LETSENCRYPT_HOST: mingwangbeta.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

  smart-redis:
    image: redis
    networks:
      - default

  smartfp-worker:
    build: .
    container_name: smartfp-worker
    volumes:
        - ./SMART_Finder:/SMART_Finder
        - ./tempuploads/:/app/tempuploads
    command: /app/run_smartfp_celery_worker.sh
    restart: on-failure
    depends_on: 
      - smart-redis
    networks:
      - default


networks:
  nginx-net:
    external:
      name: nginx-net