version: '3'

services:
  smart-web:
    build: .
    ports:
      - "6213:5000"
    command: /app/run_server.sh
    networks:
      - default
      - nginx-net
    volumes:
        - ./SMART_Finder:/SMART_Finder
        - ./logs/:/app/logs
        - ./tempuploads/:/app/tempuploads
    environment:
      VIRTUAL_HOST: mingwangbeta.ucsd.edu
      VIRTUAL_PORT: 6213
      LETSENCRYPT_HOST: mingwangbeta.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

  smartclassic-rabbitmq:
    image: rabbitmq:latest
    networks:
      - default

  smartclassic-worker:
    build:
      context: .
      dockerfile: classic.Dockerfile
    container_name: smartclassic-worker
    volumes:
        - ./SMART_Classic:/SMART_Classic
        - ./tempuploads/:/src/tempuploads
    command: /src/run_smartclassic_celery_worker.sh
    restart: on-failure
    depends_on: 
      - smartclassic-rabbitmq
    networks:
      - default

  # smartfp-redis:
  #   image: redis
  #   networks:
  #     - default

  # smartfp-worker:
  #   build: .
  #   container_name: smartfp-worker
  #   volumes:
  #       - ./SMART_Finder:/SMART_Finder
  #       - ./tempuploads/:/app/tempuploads
  #   command: /app/run_smartfp_celery_worker.sh
  #   restart: on-failure
  #   depends_on: 
  #     - smartfp-redis
  #   networks:
  #     - default

  # smartfp-tf-server:
  #   image: tensorflow/serving
  #   volumes:
  #       - ./SMART_Finder/models:/models
  #       - ./tempuploads/:/app/tempuploads
  #   restart: on-failure
  #   networks:
  #     - default
  #   environment:
  #     MODEL_NAME: HWK_sAug_1106_final_2048_cos

  # smartfp-mw-tf-server:
  #   image: tensorflow/serving
  #   volumes:
  #       - ./SMART_Finder/models:/models
  #       - ./tempuploads/:/app/tempuploads
  #   restart: on-failure
  #   networks:
  #     - default
  #   environment:
  #     MODEL_NAME: VGG16_high_aug_MW_continue


networks:
  nginx-net:
    external:
      name: nginx-net