version: '3'

services:
  smart-web:
    build: .
    ports:
      - "6213:5000"
    command: /app/run_server.sh
    volumes:
        - ./SMART_Finder:/SMART_Finder
        - ./logs/:/app/logs
        - ./tempuploads/:/app/tempuploads