name: Docker Image CI

on:
  push:
    branches: [ "classic" ]
  pull_request:
    branches: [ "classic" ]
  schedule:
   - cron:  '0 0 * * *'

jobs:

  build-docker-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # with:
      #   submodules: recursive
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile
  build-docker-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # with:
      #   submodules: recursive
    - name: Build the Docker image
      run: |
        docker build . --file classic.Dockerfile